### ISSUE TITLE
Using sandbox during developement

### ISSUE THREAD

**Issue by vincent-lwt** [hildjj/node-feedly#2]
An option for using the feedly sandbox ("sandbox.feedy.com") instead of the "cloud.feedly.com" would be nice. Thank's.

**Comment by hildjj** [comment]
Hm.  This:

```
Feedly = require('feedly');
var f = new Feedly({base:http://sandbox.feedly.com, port:8080, client_id:"", client_secret:""})
```

has worked for me in the past?

**Comment by hildjj** [comment]
And just did for me again, after I updated to this month's client secret.

**Comment by vincent-lwt** [comment]
Thank's, didn't knew I could do that.
